import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
const bytes = await readFile("native/windows-hello/publish/win-x64/UbcHello.exe");
const digest = createHash("sha256").update(bytes).digest("hex");
await writeFile("src/passwords/native.generated.ts", `// Generated by scripts/embed-hello.mjs; do not edit.\nexport const helloDigest = "${digest}";\nexport const helloBinary = "${bytes.toString("base64")}";\n`);
console.log(`Embedded Windows Hello bridge (${bytes.length} bytes, sha256=${digest})`);
